{% set name = "openff-recharge" %}
{% set version = "0.3.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 71c294a1be2b0b9dc3c222672bdcb9e14e0c64bc4f484f16ddbe77acaea8b0b0

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
  - recharge = openff.recharge.cli:cli

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - tqdm
    - numpy
    - jinja2
    - pydantic
    - openff-utilities
    - openff-units
    - openff-toolkit-base >=0.10.5
    - sqlalchemy
    - sqlite
    - typing-extensions
    - rdkit  

test:
  imports:
    - openff.recharge

about:
  home: https://github.com/openforcefield/openff-recharge
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for generating partial charges for molecules from QC data.
  description: |
    A framework for generating partial charges for molecules from QC data.
  doc_url: https://github.com/openforcefield/openff-recharge
  dev_url: https://github.com/openforcefield/openff-recharge

extra:
  recipe-maintainers:
    - simonboothroyd
