{% set name = "openff-recharge" %}
{% set version = "0.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 84d876e54bc98a92de637e7b50c2d2ab4a4720e17ffa7cc5716a19de975be385

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
  - recharge = openff.recharge.cli:cli

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - click
    - tqdm
    - jinja2
    - openff-toolkit-base >=0.11.0
    - openff-interchange-base >=0.2.0
    - sqlalchemy
    - sqlite
    - rdkit  

test:
  imports:
    - openff.recharge

about:
  home: https://github.com/openforcefield/openff-recharge
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for generating partial charges for molecules from QC data.
  description: |
    A framework for generating partial charges for molecules from QC data.
  doc_url: https://github.com/openforcefield/openff-recharge
  dev_url: https://github.com/openforcefield/openff-recharge

extra:
  recipe-maintainers:
    - simonboothroyd
    - lilyminium
    - mattwthompson
    - j-wags
