{% set name = "openff-recharge" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 94b2aae663e31b38763de7983a3208b8bc477cc7fba3cbae3a6d92c7ed90010b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
  - recharge = openff.recharge.cli:cli

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - tqdm
    - numpy
    - jinja2
    - pydantic
    - openff-utilities
    - openff-units
    - openff-toolkit-base >=0.10.2
    - sqlalchemy
    - sqlite
    - typing-extensions
    - rdkit  

test:
  imports:
    - openff.recharge

about:
  home: https://github.com/openforcefield/openff-recharge
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for generating partial charges for molecules from QC data.
  description: |
    A framework for generating partial charges for molecules from QC data.
  doc_url: https://github.com/openforcefield/openff-recharge
  dev_url: https://github.com/openforcefield/openff-recharge

extra:
  recipe-maintainers:
    - simonboothroyd
