{% set name = "openff-recharge" %}
{% set version = "0.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 35c1e2ffd9d7dd3f43c1a15ba3bd26a36c82971286be5d3cc5c4d0a7fc57dcf6

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
  - recharge = openff.recharge.cli:cli

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - click
    - tqdm
    - jinja2
    - openff-toolkit-base >=0.11.0
    - openff-interchange-base
    - sqlalchemy
    - sqlite
    - rdkit  

test:
  imports:
    - openff.recharge
  commands:
    - openff-recharge --help

about:
  home: https://github.com/openforcefield/openff-recharge
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for generating partial charges for molecules from QC data.
  description: |
    A framework for generating partial charges for molecules from QC data.
  doc_url: https://github.com/openforcefield/openff-recharge
  dev_url: https://github.com/openforcefield/openff-recharge

extra:
  recipe-maintainers:
    - simonboothroyd
    - lilyminium
    - mattwthompson
    - j-wags
