{% set name = "openff-recharge" %}
{% set version = "0.5.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 82bd48c02cd9e9681a99085f8e34a9d71fbac02320df531bb6d38ca3d2ff0033

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
  - recharge = openff.recharge.cli:cli

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - click
    - tqdm
    - jinja2
    - pydantic
    - openff-toolkit-base >=0.14.0
    - openff-interchange-base >=0.3.18
    - openff-utilities
    - openff-units >=0.2    
    - sqlalchemy
    - sqlite
    - rdkit  

test:
  imports:
    - openff.recharge
  commands:
    - openff-recharge --help

about:
  home: https://github.com/openforcefield/openff-recharge
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for generating partial charges for molecules from QC data.
  description: |
    A framework for generating partial charges for molecules from QC data.
  doc_url: https://github.com/openforcefield/openff-recharge
  dev_url: https://github.com/openforcefield/openff-recharge

extra:
  recipe-maintainers:
    - simonboothroyd
    - lilyminium
    - mattwthompson
    - j-wags
